# Matemática para Ciencia de los Datos
# Trabajo Práctico 2

Profesor: Juan Luis Crespo Mariño, basado en trabajo previo de Luis Alexánder Calvo Valverde

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: Martes 5 de agosto, a más tardar a las 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. **Roberto Jose Baltodano**
1. **Sergio D. Blanco**



---

**Pregunta 1**

Considerando que la transpuesta de una matriz es el resultado de cambiar las filas a columnas. Sea una matriz $A\in\mathbb{R}^{m\times n}$, su transpuesta se escribe como $A^{T}\in\mathbb{R}^{n\times m}$ y sus entradas están dadas por:

\begin{equation}
\left(A^{T}\right)_{i,j}=A_{j,i}.
\end{equation}

Proponga Usted dos matrices, $A\in\mathbb{R}^{4\times 3}$ y $B\in\mathbb{R}^{3\times 4}$ (no las busque en Internet, trate de proponer los valores por si mismo), y utilizando numpy muestre que las siguientes propiedades se cumplen con sus matrices propuestas.

**Note** que ni A ni B son cuadradas, y no tienen las mismas dimensiones.


**1.1 (15 puntos)**

- $\left(A^{T}\right)^{T}=A$


In [1]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from IPython.display import display, Markdown


a = np.array([ [1. , 2. , 3. ], [4. , 5. , 6. ] , [7. , 8. , 91.]])
display(Markdown("## Matriz actual   A "))
print( a )
print("-"*20 )
t = np.transpose(A)
display(Markdown("## Matriz transpuesta   T "))

print( t )
print("-"*20 )

tt = np.transpose(t)
display(Markdown("## Matriz transpuesta nuevamente TT"))
print( tt )
print("-"*20 )
print("", np.equal( a, tt))
display(Markdown(f"## Queda evienciado que A == TT es .")) 



## Matriz actual   A 

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 91.]]
--------------------


NameError: name 'A' is not defined

**1.2 (15 puntos)**

- $\left(AB\right)^{T}=B^{T}A^{T}$


In [ ]:
a = np.array([ [1. , 2. , 3. ], [4. , 5. , 6. ] , [7. , 8. , 91.]])

b = np.transpose(t)



**1.3 (15 puntos)**

Para este ejercicio, **proponga dos matrices de igual dimensionalidad**


- $\left(A+B\right)^{T}=A^{T}+B^{T}$.


---

**Pregunta 2**


Un conjunto de vectores $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \in\mathbb{R}^{m}$ se dice que es linealmente independiente, si ningún vector de tal conjunto puede ser representado como una combinación lineal del resto de vectores. De lo contrario, si uno de los vectores en tal conjunto puede ser representado como una combinación lineal del resto de vectores, entonces los vectores son linealmente dependientes, lo que se expresa como:

\begin{equation}
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
\end{equation}

para cualquier conjunto de valores escalares $\alpha_{1},\ldots,\alpha_{n-1}\in\mathbb{R}$ se dice que el vector $\vec{x}_{j}\in\mathbb{R}^{m}$ es linealmente dependiente de los vectores $\vec{x}_{i}$.


**2.1 (15 puntos)**

Proponga una matriz $A\in\mathbb{R}^{4\times 3}$, cuyos vectores columnas sean linealmente independientes, calcule su rango para mostrar que es de rango $3$ (puede utilizar matrix_rank).


**2.2 (15 puntos)**

Ahora haga los cambios necesarios a su matriz de manera que pase a rango $2$.

---

**Pregunta 3 (25 puntos)**

Utilizando el archivo "Dataset_usar.csv", haga:
- Cargue el archivo.
- Utilizando el modelo $Ax=b$
    - Conforme la matriz $A$ con las primeras 8 columnas. ------->  ok
    - Conforme el vector $b$ con la última columna de la derecha.  ------->  ok
    - Calcule el vector de pesos ($x$), del tipo $A^{-1}b=x$  ------->  ok usando pinv
    - Calcule un b_estimado con $A$ e $x$ ------->  no logro identificar como sacar el b_estimado para continuar
    - Calcule la norma 2 de la diferencia entre b y b_estimado.
    - Grafique b y b_estimado.



In [ ]:
import numpy as np
import pandas as pd

separador = "-"*40
archivo = "Datos_01.csv"

# carga el archivo en pandas
dataFrame = pd.read_csv(archivo, header = 0, delimiter=';')

# guarda el nombre de las columnas en una lista
colNames = dataFrame.columns

# muestra los primeros elementos del dataFrame
print(separador)
print("Datos en dataFrame:")
print(dataFrame.head() )

# En cada vector columna hay un atributo
# El atributo1 está en datos[:,0]
# El atributo2 está en datos[:,1]
# y así sucesivamente


# Convertir de pandas a numpy
datos = pd.DataFrame(dataFrame).to_numpy()

matriz_a = datos[:,0:6]

matriz_b = datos[:,8]

columns = matriz_a.shape[]
columns = matriz_b.shape[]