# Matemática para Ciencia de los Datos
# Trabajo Práctico 2

Profesor: Juan Luis Crespo Mariño, basado en trabajo previo de Luis Alexánder Calvo Valverde

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: Martes 5 de agosto, a más tardar a las 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. **Roberto Jose Baltodano**
1. **Sergio D. Blanco**



---

**Pregunta 1**

Considerando que la transpuesta de una matriz es el resultado de cambiar las filas a columnas. Sea una matriz $A\in\mathbb{R}^{m\times n}$, su transpuesta se escribe como $A^{T}\in\mathbb{R}^{n\times m}$ y sus entradas están dadas por:

\begin{equation}
\left(A^{T}\right)_{i,j}=A_{j,i}.
\end{equation}

Proponga Usted dos matrices, $A\in\mathbb{R}^{4\times 3}$ y $B\in\mathbb{R}^{3\times 4}$ (no las busque en Internet, trate de proponer los valores por si mismo), y utilizando numpy muestre que las siguientes propiedades se cumplen con sus matrices propuestas.

**Note** que ni A ni B son cuadradas, y no tienen las mismas dimensiones.


**1.1 (15 puntos)**

- $\left(A^{T}\right)^{T}=A$


In [12]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from IPython.display import display, Markdown


a = np.array([ [1. , 2. , 3. ], [4. , 5. , 6. ] , [7. , 8. , 91.]])
display(Markdown("## Matriz actual   A "))
print( a )
print("-"*20 )
t = np.transpose(a)
display(Markdown("## Matriz transpuesta   T "))

print( t )
print("-"*20 )

tt = np.transpose(t)
display(Markdown("## Matriz transpuesta nuevamente TT"))
print( tt )
print("-"*20 )
print("", np.equal( a, tt))
display(Markdown(f"## Queda evienciado que A == TT es .")) 



## Matriz actual   A 

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 91.]]
--------------------


## Matriz transpuesta   T 

[[ 1.  4.  7.]
 [ 2.  5.  8.]
 [ 3.  6. 91.]]
--------------------


## Matriz transpuesta nuevamente TT

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 91.]]
--------------------
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Queda evienciado que A == TT es .

**1.2 (15 puntos)**

- $\left(AB\right)^{T}=B^{T}A^{T}$


In [13]:
a = np.array([ [1. , 2. , 3. ], [4. , 5. , 6. ] , [7. , 8. , 91.]])

b = np.transpose(t)



**1.3 (15 puntos)**

Para este ejercicio, **proponga dos matrices de igual dimensionalidad**


- $\left(A+B\right)^{T}=A^{T}+B^{T}$.


---

**Pregunta 2**


Un conjunto de vectores $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \in\mathbb{R}^{m}$ se dice que es linealmente independiente, si ningún vector de tal conjunto puede ser representado como una combinación lineal del resto de vectores. De lo contrario, si uno de los vectores en tal conjunto puede ser representado como una combinación lineal del resto de vectores, entonces los vectores son linealmente dependientes, lo que se expresa como:

\begin{equation}
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
\end{equation}

para cualquier conjunto de valores escalares $\alpha_{1},\ldots,\alpha_{n-1}\in\mathbb{R}$ se dice que el vector $\vec{x}_{j}\in\mathbb{R}^{m}$ es linealmente dependiente de los vectores $\vec{x}_{i}$.


**2.1 (15 puntos)**

Proponga una matriz $A\in\mathbb{R}^{4\times 3}$, cuyos vectores columnas sean linealmente independientes, calcule su rango para mostrar que es de rango $3$ (puede utilizar matrix_rank).


**2.2 (15 puntos)**

Ahora haga los cambios necesarios a su matriz de manera que pase a rango $2$.

---

**Pregunta 3 (25 puntos)**

Utilizando el archivo "Dataset_usar.csv", haga:
- Cargue el archivo.
- Utilizando el modelo $Ax=b$
    - Conforme la matriz $A$ con las primeras 8 columnas. ------->  ok
    - Conforme el vector $b$ con la última columna de la derecha.  ------->  ok
    - Calcule el vector de pesos ($x$), del tipo $A^{-1}b=x$  ------->  ok usando pinv
    - Calcule un b_estimado con $A$ e $x$ ------->  no logro identificar como sacar el b_estimado para continuar
    - Calcule la norma 2 de la diferencia entre b y b_estimado.
    - Grafique b y b_estimado.



In [14]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


separador = "-"*40
archivo = "Dataset_usar.csv"

# carga el archivo en pandas
dataFrame = pd.read_csv(archivo, header = 0, delimiter=';')

# guarda el nombre de las columnas en una lista
colNames = dataFrame.columns

# muestra los primeros elementos del dataFrame
print(separador)
print("Datos en dataFrame:")
print(dataFrame.head() )

----------------------------------------
Datos en dataFrame:
   bias    Length  Diameter    Height     Whole   Shucked  Sex_Female  \
0     1  0.186567  0.155963  0.195652  0.011688  0.333333           0   
1     1  0.813433  0.761468  0.826087  0.433327  0.333333           1   
2     1  0.410448  0.376147  0.369565  0.074022  0.333333           1   
3     1  0.537313  0.504587  0.500000  0.143085  0.333333           1   
4     1  0.507463  0.495413  0.565217  0.146981  0.333333           0   

   Sex_Masculine  Shellweight  
0              1        0.010  
1              0        0.435  
2              0        0.068  
3              0        0.096  
4              1        0.144  


In [15]:
# Convertir de pandas a numpy
datos = pd.DataFrame(dataFrame).to_numpy()

print("saca las columnas de la matriz A")
matriz_a = datos[:,0:8]

print("saca la columna de la matriz B o el vector b")
matriz_b = datos[:,8]

print("verificacion....")
print(matriz_a[1,:])
print(matriz_b[1])

print("genera la pseudo inversa")

inv_matriz_a = np.linalg.pinv(matriz_a)

print("procede a la multiplicación para ver los pesos del vector x")
print(" ")

pesos_x = np.matmul(inv_matriz_a, matriz_b)

print("Los valores de x son:  ")
print(pesos_x)

print("Se aplica la transpuesta de los valores de x  para sacar b_estimado " )

pesos_x_t = np.transpose(pesos_x)
b_estimado = np.matmul(matriz_a, pesos_x_t)

punto_b = matriz_b[0:2]
punto_b_estimado =b_estimado[0:2]


print(" ")
print("-"*40)
print(" Valor definido ",punto_b)
print("-"*40)
print(" Valor estimado ", punto_b_estimado)
print("-"*40)
print("-"*40)

# Establece la base del origen de cada vector
# x = np.array([0.,0.] )
# y = np.array([0.,0.] )

# fig, ax = plt.subplots()

# ax.quiver(x, y, punto_b, punto_b_estimado ,color=["r","b"],angles='xy', scale_units='xy', scale=1)

# ax.axis([-0.2,1.,-0.2,1.])
# ax.set_aspect('equal')
# plt.show()

# print("-"*40)
# print("-"*40)

# print(" En el gráfico podemos apreciar que solo se muestra un solo vector," )
# print("eso indica que ambos vectores  son colineales y van de la misma dirección")


saca las columnas de la matriz A
saca la columna de la matriz B o el vector b
verificacion....
[1.         0.81343284 0.76146789 0.82608696 0.43332743 0.33333333
 1.         0.        ]
0.435
genera la pseudo inversa
procede a la multiplicación para ver los pesos del vector x
 
Los valores de x son:  
[-4.86806821e+09 -7.10562178e-02  2.04691410e-03  8.44010112e-02
  8.93133383e-01 -7.68537327e-02  4.86806821e+09  4.86806821e+09]
Se aplica la transpuesta de los valores de x  para sacar b_estimado 
 
----------------------------------------
 Valor definido  [0.01  0.435]
----------------------------------------
 Valor estimado  [0.00796986 0.39447975]
----------------------------------------
----------------------------------------


In [25]:
import matplotlib.pyplot as plt
import numpy as np

b1= matriz_b[0:3]


b2= b_estimado[0:3]

print (b1 + b2)


mat_1 = np.array([b1])
mat_2 = np.array([b2])
print(np.concatenate((mat_1, mat_2)))


[0.01796986 0.82947975 0.13088719]
[[0.01       0.435      0.068     ]
 [0.00796986 0.39447975 0.06288719]]
