# Matemática para Ciencia de los Datos
- Documento base: Saúl Calderón, Žiga Emeršič, Ángel García, Blaž Meden, Felipe Meza, Martín Solís, Juan Esquivel, Mauro Méndez, Manuel Zumbado, Luis-Alexánder Calvo-Valverde.

## Video

https://www.youtube.com/watch?v=yt3eoYvGel0

# Determinante de una matriz

El determinante de una matriz cuadrada $A\in\mathbb{R}^{n\times n}$ es una función denotada con $\textrm{det}\left(A\right):\mathbb{R}^{n\times n}\rightarrow\mathbb{R}$. Antes de detallar la fórmula que define al determinante, examinaremos la interpretación geométrica del determinante. Sea una matriz compuesta por múltiples filas:


\begin{equation}
A=\begin{bmatrix}- & \vec{a}_{1,:}^{T} & -\\
- & \vec{a}_{2,:}^{T} & -\\
 & \vdots\\
- & \vec{a}_{n,:}^{T} & -
\end{bmatrix}
\end{equation}

considere el conjunto de puntos $S\subset\mathbb{R}^{n}$ formado al tomar todas las combinaciones lineales posibles de los vectores fila $\vec{a}_{i,:}^{T}$, donde los coeficientes de tal combinación lineal cumplen que $0\leq\alpha_{i}\leq1,i=1,\ldots,n$, lo cual formalmente se denota como:

\begin{equation}
S=\left\{ \vec{v}\in\mathbb{R}^{n}:\vec{v}=\sum_{i=1}^{n}\alpha_{i}\vec{a}_{i,:},\qquad0\leq\alpha_{i}\leq1,i=1,\ldots,n\right\}
\end{equation}

El valor absoluto del determinante de la matriz $A$, $\left|\textrm{det}\left(A\right)\right|$, corresponde a una medida del volumen de todo el conjunto $S$.

Por ejemplo, para la matriz $A\in\mathbb{R}^{2\times2}$:

\begin{equation}
A=\begin{bmatrix}1 & 3\\
3 & 2
\end{bmatrix}
\end{equation}

cuyos vectores fila están dados por:

\begin{equation}
\vec{a}_{1,:}=\begin{bmatrix}1\\
3
\end{bmatrix}\qquad\vec{a}_{2,:}=\begin{bmatrix}3\\
2
\end{bmatrix}
\end{equation}

![](https://drive.google.com/uc?export=view&id=1NQT1S63yH27AE4cO1d_YIsi5CkBmwfZ-)


se muestra en la Figura, sombreado, el conjunto de puntos $S$. Observe que el punto ``extremo'' $\vec{a}_{1,:}+\vec{a}_{2,:}=\begin{bmatrix}4\\
5
\end{bmatrix}$, viene dado cuando $\alpha_{1}=\alpha_{2}=1$. El determinante para una matriz de $2\times2$ se define como:

\begin{equation}
\textrm{det}\left(\begin{bmatrix}a & b\\
c & d
\end{bmatrix}\right)=a\,d-b\,c
\end{equation}

y para cualquier matriz de $n\times n$ dimensiones, el determinante se define recursivamente como:

\begin{equation}
\textrm{det}\left(A\right)=A_{1,1}\textrm{det}\left(A_{\backslash1,\backslash1}\right)-A_{1,2}\textrm{det}\left(A_{\backslash1,\backslash2}\right)+\ldots\pm A_{1,n}\textrm{det}\left(A_{\backslash1,\backslash n}\right)
\end{equation}

lo cual es equivalente también a escoger cualquier fila o columna a eliminar:

\begin{equation}
\textrm{det}\left(A\right)=\sum_{i=1}^{n}\left(-1\right)^{i+j}A_{i,j}\left|A_{\backslash i,\backslash j}\right|=\sum_{j=1}^{n}\left(-1\right)^{i+j}A_{i,j}\left|A_{\backslash i,\backslash j}\right|
\end{equation}

Observe que el determinante consiste en la combinación lineal de los determinantes de las submatrices resultantes de eliminar la fila y columna $i$ (denotado como $\textrm{det}\left(A_{\backslash i,\backslash j}\right)$), multiplicado por el elemento $A_{1,i}$. Con la matriz de ejemplo $A=\begin{bmatrix}1 & 3\\ 3 & 2 \end{bmatrix}$ , el determinante viene entonces dado por: $\textrm{det}\left(A\right)=1\cdot2-3\cdot3=-7$, y tomando su valor absoluto, se tiene que $\left|\textrm{det}\left(A\right)\right|=7$, lo que corresponde al área del paralelogramo formado por el conjunto de puntos $S$ (en $n$ dimensiones, se refiere como paralelótopo).


<h3 align="center">Región $S$ de ejemplo.</h3>

Las siguientes son propiedades de la función determinante $\textrm{det}\left(A\right)$ para una matriz cuadrada $A\in\mathbb{R}^{n\times n}$ :

- El volumen de un hipercubo unitario es $\textrm{det}\left(I\right)=1$.
- Homogeneidad: Sea un escalar $s\in\mathbb{R}$, $\textrm{det}\left(s\,A\right)=s\,\textrm{det}\left(A\right)$
- $\textrm{det}\left(A\right)=\textrm{det}\left(A^{T}\right)$
- $\textrm{det}\left(A\,B\right)=\textrm{det}\left(A\right)\,\textrm{det}\left(B\right)$
- $\textrm{det}\left(A\right)=0$, implica que $A$ es una matriz singular (no invertible), por lo que entonces no tiene rango completo, y sus columnas son **linealmente dependientes**, lo que implica además la superficie $S$ no tiene volumen, al ser los vectores combinación lineal.
- $\textrm{det}\left(A^{-1}\right)=1/\textrm{det}\left(A\right)$


In [ ]:
import numpy as np
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float32)
m2 = np.array([[1,3],[3,2]], dtype=np.float32)
m3 = np.array([[3,0,4],[2,5,6],[1,4,8]], dtype=np.float32)

print(m1)
print(m2)
print(m3)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 3.]
 [3. 2.]]
[[3. 0. 4.]
 [2. 5. 6.]
 [1. 4. 8.]]


In [ ]:
from numpy.linalg import matrix_rank
# esta da cero
print(np.linalg.det(m1))

# esta da -7
print(np.linalg.det(m2))

# esta da -7
print(np.linalg.det(m3))


print(matrix_rank(m1))
print(matrix_rank(m2))
print(matrix_rank(m3))


0.0
-7.0
60.0
2
2
3


In [ ]:
m2 = np.array([[10,1],[3,2]], dtype=np.float32)
print(np.linalg.det(m2))

17.0


In [ ]:
eje = np.array([[1,3,5],[8,4,1],[3,2,4]], dtype=np.float32)
print(np.linalg.det(eje))


-53.0
