# Matemática para Ciencia de los Datos
# Trabajo Práctico 3

Profesor: Juan Luis Crespo Mariño (basado en trabajo previo de Luis Alexánder Calvo Valverde)

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: 12 de agosto de 2025, hora límite 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. **Nombre_Estudiante_1**
1. **Nombre_Estudiante_2**


---

**Pregunta 1**



Se puede demostrar que para los vectores generadores de un subespacio $E=\textrm{espacioGenerado}\left\{ \vec{v}_{1},\vec{v}_{2},\ldots,\vec{v}_{m}\right\}$ , con $V=\left[\vec{v}_{1},\vec{v}_{2},\ldots,\vec{v}_{m}\right]$,con $\vec{v}_{m}\in\mathbb{R}^{n}$ si son ortonormales, la ecuación de la proyección de un vector $\vec{u}\in\mathbb{R}^{n}$ originalmente dada por:

$$\textrm{proy}\left(\vec{u};V\right)=\textrm{argmin}_{\vec{v}\in E}\left\Vert \vec{v}-\vec{u}\right\Vert _{2}=V\,\left(V^{T}V\right)^{-1}V^{T}\vec{u}$$

se puede reescribir como:

$$\textrm{proy}\left(\vec{u};V\right)=\textrm{argmin}_{\vec{v}\in E}\left\Vert \vec{v}-\vec{u}\right\Vert _{2}=V\,V^{T}\vec{u}$$

con $V\in\mathbb{R}^{n\times m}$.









**1.1 (25 puntos)**

Utilizando numpy, proponga una matriz ortonormal de dimensiones 3x3, para ello utilice una fuente como "Proceso de ortonormalización de  Gram - Schmidt" (https://blog.nekomath.com/algebra-lineal-i-proceso-de-gram-schmidt/) para producir una matriz ortonormal a partir de una matriz que no es ni ortonormal ni ortogonal.

Finalmente muestre en numpy que su matriz resultante es ortonormal ($V$).



In [2]:
import numpy as np

# Se propone una matriz 3x3 cualquiera
matrizPropuesta = np.array([[5., 16., 87.], [10., 6., 18.], [4., 4., 83.]])

def normalizar(x):
    n = np.linalg.norm(x)
    if n == 0:
        raise ValueError("Vector cero: el conjunto no es linealmente independiente.")
    return x / n

def gram_schmidt_recursivo(V: np.ndarray) -> np.ndarray:
    if len(V) == 0:
        return []
    U_prev = gram_schmidt_recursivo(V[:-1])
    v = V[-1].astype(float)
    # Quita proyecciones secuencialmente con el v actualizado
    for u in U_prev:
        v = v - np.dot(v, u) * u
    u = normalizar(v)
    return U_prev + [u]
    
    
# Matriz ortonormal de la matriz propuesta
q = np.array(gram_schmidt_recursivo(matrizPropuesta))
print(f"Matriz ortonormal resultante: {q}")

print("Para mostrar que es una matriz ortonormal, se verifica que Qt*Q=I donde Q es la matriz ortogonal resultante, Qt es la transpuesta de dicha matriz e I es la matriz identidad")
matrizAVerificar = np.round(np.matmul(np.transpose(q), q), 10)
matrizIdentidad = np.eye(q.shape[0])
print(f"Es una matriz ortonormal? \n{matrizAVerificar} \n=\n {matrizIdentidad}")

# Para mostrar que es ortonormal Qt*Q=I
print(np.array_equal(matrizAVerificar, matrizIdentidad))


Matriz ortonormal resultante: [[ 0.05643326  0.18058645  0.98193881]
 [ 0.95723476  0.26973381 -0.10461971]
 [ 0.283755   -0.94584999  0.15764167]]
Para mostrar que es una matriz ortonormal, se verifica que Qt*Q=I donde Q es la matriz ortogonal resultante, Qt es la transpuesta de dicha matriz e I es la matriz identidad
Es una matriz ortonormal? 
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]] 
=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True


**1.2 (15 puntos)**

Proponga un vector $\vec{u}$ y programe en numpy las operaciones algebraicas siguientes (tome $V$ del paso anterior).

$V\,\left(V^{T}V\right)^{-1}V^{T}\vec{u}$

y,

$V\,V^{T}\vec{u}$


In [ ]:
import numpy as np
from numpy import linalg as LA

def projectInvertible(y, A):
  """
  y: column vector, 2d array
  A: n x m matrix, 2d array
  """
  At = np.transpose(A)
  invMatrix = LA.inv(np.matmul(At,A))
  return np.matmul( np.matmul(np.matmul(A,invMatrix), At), y)

def projectInvertibleOrt(y, A):
  """
  y: column vector, 2d array
  A: n x m matrix, 2d array
  """
  At = np.transpose(A)
  return np.matmul(A, np.matmul(At, y))

u = np.array([45., 32.5, -17.45])
proy1 = projectInvertible(u, q)
proy2 = projectInvertibleOrt(u, q)

print(f"V(VtV)^-1Vtu = {proy1}")
print(f"VVtu = {proy2}")

print("Se puede observar que V(VtV)^-1Vtu es igual a VVtu")

V(VtV)^-1Vtu = [ 45.    32.5  -17.45]
VVtu = [ 45.    32.5  -17.45]
Se puede observar que V(VtV)^-1Vtu es igual a VVtu


**1.3 (10 puntos)**

Programe en python para calcular el error de proyección obtenido para los casos del punto **1.2**.

In [36]:
def calculateProjectionError(v, y):
  """
  Calculate projection error by using the euclidian distance
  """
  return LA.norm(v - y, 2)

print("Error de proyección: ")
error = calculateProjectionError(proy1, u)
print(error)

Error de proyección: 
0.0


---

**Pregunta 2 (10 puntos)**


Programe en python la función calculeDet2, que recibe como parámetro una matriz cuadrada de dimensiones 2x2, llamada M, y retorna el determinante de esa matriz. Usted debe programar las operaciones matemáticas necesarias, no utilizar una función tipo det para calcularla. Pruébela con dos matrices que Usted proponga.

def calculeDet2( M ):





In [34]:
import numpy as np

def calculeDet2(M: np.ndarray) -> float:
  """
  Calcula determinante para matrices 2x2
  """
  if len(M) != 2 or M.shape[0] != 2 or M.shape[1] != 2:
    raise Exception("Metodo exclusivo para calcular la determinante de una matriz 2x2")
  
  return M[0,0]*M[1,1] - M[0,1]*M[1,0]

m1 = np.array([[1,3],[3,2]], dtype=np.float32)
print(f"Verificando la misma matriz de la clase 4\n{m1}")
print(calculeDet2(m1))
print("\nMatriz aleatoria y comparando valores con funcion hecha y funcion det")
m2 = np.array([[45,-39.5],[1001,2002]], dtype=np.float32)
print(calculeDet2(m2))
print(np.linalg.det(m2))

Verificando la misma matriz de la clase 4
[[1. 3.]
 [3. 2.]]
-7.0

Matriz aleatoria y comparando valores con funcion hecha y funcion det
129629.5
129629.5


---

**Pregunta 3 (10 puntos)**


Programe en python la función calculeDet3, que recibe como parámetro una matriz cuadrada de dimensiones 3x3, llamada M, y retorna el determinante de esa matriz. Usted debe programar las operaciones matemáticas necesarias, no utilizar una función de numpy tipo det para calcularla (sí puede usar función que programó en la **Pregunta 2**). Pruébela con dos matrices que Usted proponga.

def calculeDet3( M ):






In [35]:
import numpy as np

def calculeDet3(M: np.ndarray) -> float:
  """
  Calcula determinante para matrices 3x3
  """
  if len(M) != 3 or M.shape[0] != 3 or M.shape[1] != 3:
    raise Exception("Metodo exclusivo para calcular la determinante de una matriz 3x3")
  
  return (M[0,0] * calculeDet2(M[1:3, 1:3])) - (M[0,1] * calculeDet2(M[1:3, [0, 2]])) + (M[0,2] * calculeDet2(M[1:3, 0:2]))

m3 = np.array([[3,0,4],[2,5,6],[1,4,8]], dtype=np.float32)
print(f"Verificando la misma matriz de la clase 4\n{m3}")
print(calculeDet3(m3))

print("\nMatriz aleatoria y comparando valores con funcion hecha y funcion det")
m4 = np.array([[10,6,18],[4,4,83], [16,5,87]], dtype=np.float32)
print(calculeDet3(m4))
print(np.linalg.det(m4))

Verificando la misma matriz de la clase 4
[[3. 0. 4.]
 [2. 5. 6.]
 [1. 4. 8.]]
60.0

Matriz aleatoria y comparando valores con funcion hecha y funcion det
4418.0
4418.0


---

**Pregunta 4 (15 puntos)**

Se tiene que:

$$\textrm{det}\left(A\,B\right)=\textrm{det}\left(A\right)\,\textrm{det}\left(B\right)$$

Proponga dos matrices de 4x4 ( $A$ e $B$) y programando en numpy muestre esta igualdad (puede usar de numpy las funciones det y la de multiplicar matrices).






---

**Pregunta 5 (15 puntos)**


Utilizando el archivo "Dataset_usar.csv", haga:
- Cargue el archivo.
- Muestre cuántas filas por cuántas columnas tiene el conjunto de datos.
- Utilizando el modelo $Ax=b$
    - Conforme la matriz $A$ con todas las columnas menos la última de la derecha.
    - Conforme el vector $b$ con la última columna de la derecha.
    - Calcule el vector de pesos ($x$), utilizando el concepto de mínimos cuadrados $\left(A^{T}A\right)^{-1}A^{T}\vec{b}$
    - Calcule un b_estimado con $A$ e $x$
    - Calcule la norma 2 de la diferencia entre b y b_estimado.
    - Grafique b y b_estimado.

