# Matemática para Ciencia de los Datos
# Trabajo Práctico 3

Profesor: Juan Luis Crespo Mariño (basado en trabajo previo de Luis Alexánder Calvo Valverde)

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: 12 de agosto de 2025, hora límite 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. **Nombre_Estudiante_1**
1. **Nombre_Estudiante_2**


---

**Pregunta 1**



Se puede demostrar que para los vectores generadores de un subespacio $E=\textrm{espacioGenerado}\left\{ \vec{v}_{1},\vec{v}_{2},\ldots,\vec{v}_{m}\right\}$ , con $V=\left[\vec{v}_{1},\vec{v}_{2},\ldots,\vec{v}_{m}\right]$,con $\vec{v}_{m}\in\mathbb{R}^{n}$ si son ortonormales, la ecuación de la proyección de un vector $\vec{u}\in\mathbb{R}^{n}$ originalmente dada por:

$$\textrm{proy}\left(\vec{u};V\right)=\textrm{argmin}_{\vec{v}\in E}\left\Vert \vec{v}-\vec{u}\right\Vert _{2}=V\,\left(V^{T}V\right)^{-1}V^{T}\vec{u}$$

se puede reescribir como:

$$\textrm{proy}\left(\vec{u};V\right)=\textrm{argmin}_{\vec{v}\in E}\left\Vert \vec{v}-\vec{u}\right\Vert _{2}=V\,V^{T}\vec{u}$$

con $V\in\mathbb{R}^{n\times m}$.









**1.1 (25 puntos)**

Utilizando numpy, proponga una matriz ortonormal de dimensiones 3x3, para ello utilice una fuente como "Proceso de ortonormalización de  Gram - Schmidt" (https://blog.nekomath.com/algebra-lineal-i-proceso-de-gram-schmidt/) para producir una matriz ortonormal a partir de una matriz que no es ni ortonormal ni ortogonal.

Finalmente muestre en numpy que su matriz resultante es ortonormal ($V$).

Para validar esto: 

Para toda matriz ortonormal 

# $U\in\mathbb{R}^{n\times n}$ 

Se cumple que: 

# $U^{T}U=I=U\,U^{T}$



In [5]:
import numpy as np

def gram_schmidt_orthonormal(mat):
    """
    Aplica el proceso de Gram-Schmidt para obtener una base ortonormal
    a partir de una matriz cuyas columnas son vectores.
    """
    tmp_a = np.copy(mat).astype(np.float64) # Se crea una instacia local 
    n = tmp_a.shape[1]
    for j in range(n):
        # Para cada vector en las Columna j se debe encontrar la proyección perpendicular
        # de los vectores ortogonales previos.
        for k in range(j):
            tmp_a[:, j] -= np.dot(tmp_a[:, k], tmp_a[:, j]) * tmp_a[:, k]
        # 
        # Normalizar la matriz
        # el siguiente IF, lo que realiza es que verifica que la norma del vector sea mayor que 0 
        # para asegurarse que no tener error en la normalización. 
        if np.isclose(np.linalg.norm(tmp_a[:, j]), 0, rtol=1e-15, atol=1e-14, equal_nan=False):
            tmp_a[:, j] = np.zeros(tmp_a.shape[0])
        else:    
            tmp_a[:, j] = tmp_a[:, j] / np.linalg.norm(tmp_a[:, j])
    return tmp_a

# Ejemplo de uso
a = np.array([
    [16.0, 25.0, 99.0],
    [22.0, 44.0, 24.0],
    [0.0, 2.0, 18.0]
])
q = gram_schmidt_orthonormal(a)
print("Matriz Original:")
print(a)
print("-"*40)

print("Matriz ortonormal:")
print(q)
print("-"*40)
q_t = np.transpose(q)  # se puede usar  q.T  el cual devuelve de una vez la tarnspuesta 

q1_result = q.T@q   # se puede utilizar el @ en vez de matmul ya que esta 
                    # sobrecarga del operador esta en la misma biblioteca. 

print(q1_result)
print("-"*40)
print("Matriz redondeando a 10 digitos:")
print(np.round(q1_result,10))



Matriz Original:
[[16. 25. 99.]
 [22. 44. 24.]
 [ 0.  2. 18.]]
----------------------------------------
Matriz ortonormal:
[[ 0.5881717  -0.762548    0.26939673]
 [ 0.80873608  0.55458037 -0.1959249 ]
 [ 0.          0.33310834  0.94288856]]
----------------------------------------
[[ 1.00000000e+00  9.69092470e-16  1.96236954e-15]
 [ 9.69092470e-16  1.00000000e+00 -1.68801183e-16]
 [ 1.96236954e-15 -1.68801183e-16  1.00000000e+00]]
----------------------------------------
Matriz redondeando a 10 digitos:
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


**1.2 (15 puntos)**

Proponga un vector $\vec{u}$ y programe en numpy las operaciones algebraicas siguientes (tome $V$ del paso anterior).

$V\,\left(V^{T}V\right)^{-1}V^{T}\vec{u}$

y,

$V\,V^{T}\vec{u}$


In [ ]:
u = np.array([[43.0, 232.0, 453.0]])

u_result = q_t @ np.linalg.inv(q_t.T@q_t) @ q_t.T * u

print("-"*40)
print (u_result)
print("-"*40)

u_result2 = q_t @ q_t.T * u

print (u_result2)
print("-"*40)

----------------------------------------
[[ 4.30000000e+01 -2.16793800e-14  8.93170131e-15]
 [-3.53788412e-15  2.32000000e+02 -2.90461446e-14]
 [ 3.58827431e-17  3.75515848e-15  4.53000000e+02]]
----------------------------------------
[[ 4.30000000e+01  2.24829453e-13  8.88953403e-13]
 [ 4.16709762e-14  2.32000000e+02 -7.64669361e-14]
 [ 8.43818904e-14 -3.91618746e-14  4.53000000e+02]]


**1.3 (10 puntos)**

Programe en python para calcular el error de proyección obtenido para los casos del punto **1.2**.

---

**Pregunta 2 (10 puntos)**


Programe en python la función calculeDet2, que recibe como parámetro una matriz cuadrada de dimensiones 2x2, llamada M, y retorna el determinante de esa matriz. Usted debe programar las operaciones matemáticas necesarias, no utilizar una función tipo det para calcularla. Pruébela con dos matrices que Usted proponga.

def calculeDet2( M ):





---

**Pregunta 3 (10 puntos)**


Programe en python la función calculeDet3, que recibe como parámetro una matriz cuadrada de dimensiones 3x3, llamada M, y retorna el determinante de esa matriz. Usted debe programar las operaciones matemáticas necesarias, no utilizar una función de numpy tipo det para calcularla (sí puede usar función que programó en la **Pregunta 2**). Pruébela con dos matrices que Usted proponga.

def calculeDet3( M ):






---

**Pregunta 4 (15 puntos)**

Se tiene que:

$$\textrm{det}\left(A\,B\right)=\textrm{det}\left(A\right)\,\textrm{det}\left(B\right)$$

Proponga dos matrices de 4x4 ( $A$ e $B$) y programando en numpy muestre esta igualdad (puede usar de numpy las funciones det y la de multiplicar matrices).






---

**Pregunta 5 (15 puntos)**


Utilizando el archivo "Dataset_usar.csv", haga:
- Cargue el archivo.
- Muestre cuántas filas por cuántas columnas tiene el conjunto de datos.
- Utilizando el modelo $Ax=b$
    - Conforme la matriz $A$ con todas las columnas menos la última de la derecha.
    - Conforme el vector $b$ con la última columna de la derecha.
    - Calcule el vector de pesos ($x$), utilizando el concepto de mínimos cuadrados $\left(A^{T}A\right)^{-1}A^{T}\vec{b}$
    - Calcule un b_estimado con $A$ e $x$
    - Calcule la norma 2 de la diferencia entre b y b_estimado.
    - Grafique b y b_estimado.

