# Matemática para Ciencia de los Datos
- Documento base: Saúl Calderón, Žiga Emeršič, Ángel García, Blaž Meden, Felipe Meza, Martín Solís, Juan Esquivel, Mauro Méndez, Manuel Zumbado, Luis-Alexánder Calvo-Valverde.


## Video
Opcional, aplicación futura, PCA: https://www.youtube.com/watch?v=AniiwysJ-2Y

# Auto valores y auto vectores

Dada una matriz cuadrada $A \in \mathbb{R}^{nxn}$, decimos que $\lambda \in \mathbb{C}$ es un auto valor de $A$ y $\vec{x} \in \mathbb{C}^n$ es un auto vector si:

\begin{equation}
A\vec{x}=\lambda\vec{x}, \vec{x} \ne 0
\end{equation}

Si se concibe la matriz $A$ como una transformación de vectores (i.e. al multiplicar $A$ por $\vec{x}$, estamos cambiando el vector), la igualdad anterior implica que $\vec{x}$ solo cambia en escala. Intuitivamente, estamos interesados en todos los vectores $\vec{x}$ que apuntan en la misma dirección, después de ser transformados por $A$.


Los auto-vectores son vectores normalizados (con magnitud unitaria), puesto que cualquier vector escalado de $\vec{x}$, $\vec{v}=c\,\vec{x}$ hace que la ecuación $A\,\vec{v}=\lambda\vec{v}$ se siga cumpliendo.

Ahora, se tiene que:
$$A\,\vec{x}-\lambda\vec{x}=\left(A - \lambda I\right)\vec{x}=0,\qquad\vec{x}\neq0$$

La ecuación anterior tiene solución no nula o no-cero si y solo sí la matriz $\left(A - \lambda I \right)$ tiene un espacio nulo no vacío, lo cual es el caso si y solo sí tal matriz es singular (no-invertible), por lo que en términos del determinante debe cumplir que: $\textrm{det}\left(\left(A- \lambda I \right )\right)=0$.

Esto pues en general, si un sistema de ecuaciones $A\vec{x}=\vec{b}$, se tiene que A es invertible, existe entonces una solución única $\vec{x}=A^{-1}\vec{b}$. Si la matriz A no es invertible, existen múltiples e infinitas soluciones.

De esta forma, con el cálculo del determinante, se construye el polinomio en términos de la variable $\lambda$ y de grado $n$, para lo cual se encuentran las raíces de tal polinomio. Una vez conocidos los auto-valores $\lambda$, se procede a buscar sus autovectores correspondientes $\vec{x}$, resolviendo la ecuación matricial $\left(A - \lambda I \right)\vec{x}=0$.

Video - Interpretación geométrica: https://www.youtube.com/watch?v=Gx0PaWI9eYo&list=PLIb_io8a5NB2DddFf-PwvZDCOUNT1GZoA&index=14

Por ejemplo, para la siguiente matriz queremos determinar sus auto valores y auto vectores:

$
A= \begin{bmatrix}
0 & 1\\
1 & 0
\end{bmatrix}
$

Por lo tanto, debemos encontrar tanto los vectores $\vec{x}$ como los valores $\lambda$ dados por:

$
\begin{bmatrix}
0 & 1\\
1 & 0
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}=
\lambda
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}
$

El procedimiento general para razonar sobre este tipo de problema nos lleva a primero a pensar en los valores de $\lambda$. Para esta matriz tenemos $\lambda_1=1, \lambda_2=-1$. A partir de esta observación podemos también proponer los auto vectores que hacen cumplir la igualdad.

Para $\lambda = 1$:

$
\begin{bmatrix}
0 & 1\\
1 & 0
\end{bmatrix}
\begin{bmatrix}
1\\
1
\end{bmatrix}=
1
\begin{bmatrix}
1\\
1
\end{bmatrix}
$

y para $\lambda = -1$:

$
\begin{bmatrix}
0 & 1\\
1 & 0
\end{bmatrix}
\begin{bmatrix}
-1\\
1
\end{bmatrix}=
\begin{bmatrix}
1\\
-1
\end{bmatrix}=
-1
\begin{bmatrix}
-1\\
1
\end{bmatrix}
$

Y los auto-vectores son:

$
\begin{bmatrix}
1\\
1
\end{bmatrix}
y
\begin{bmatrix}
-1\\
1
\end{bmatrix}
$




## Cálculo de auto valores

El problema general que se tiene radica en tener 2 incógnitas en la ecuación $A\vec{x}=\lambda\vec{x}$. Podemos reescribir la igualdad de la siguiente forma:

$
\begin{equation}
(A-\lambda \textrm{I}) \vec{x} = 0
\end{equation}
$

La igualdad anterior se refiere al espacio nulo de la matriz $(A-\lambda \textrm{I})$. Si la matriz **no** fuera singular, tendría una solución única. Sin embargo, en este caso, debe ser que existen múltiples soluciones, por lo que la matriz debe ser singular. El determinante de una matriz singular es cero, y podemos utilizar esta observación para buscar los valores $\lambda$

\begin{equation}
\textrm{det}(A-\lambda \textrm{I}) = 0
\end{equation}

A manera de ejemplo, dado:

$A=\begin{bmatrix}3 & 1\\ 1 & 3\end{bmatrix}$

y

$\lambda I = \lambda \begin{bmatrix}1 & 0\\ 0 & 1\end{bmatrix}$

queremos calcular el determinante de $(A-\lambda \textrm{I})$:

\begin{equation}
\textrm{det}\left(\begin{bmatrix}3 - \lambda & 1\\ 1 & 3 - \lambda\end{bmatrix}\right)=0 \\
(3 - \lambda)^2 - 1=0 \\
\lambda^2 - 6 \lambda + 8 = 0
\end{equation}

Por lo tanto, se puede llegar a que $\lambda_1=4$ y $\lambda_2=2$

Una observación interesante es que los coeficientes de 6 y 8 en la ecuación cuadrática representan la traza y el determinante de $A$ (esperable en matriz cuadrada $2x2$)


* Ver ejemplo de cálculo (Ejemplo 1): https://aga.frba.utn.edu.ar/autovalores-autovectores-definiciones-propiedades/



In [ ]:
import numpy as np

# Ejemplo de solución de ecuaciones:

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.roots.html

# para el ejemplo anterior: coef de x^2=1, coef de x^1=-7, coef de x^0=10
coeff = [1., -6., 8]

# segundo ejemplo
#coeff = [1., -7., 10.]
solucion = np.roots(coeff)
print("Soluciones: ", solucion)

Soluciones:  [4. 2.]


## Cálculo de auto vectores
Una vez conocidos los valores $\lambda$ sólo resta sustituir como escalares que multiplican la matriz identidad en la ecuación:


\begin{equation}
(A-\lambda \textrm{I}) \vec{x} = 0
\end{equation}


Esto genera dos casos para $\lambda_1=4$ y $\lambda_2=2$, recordando que:

$A=\begin{bmatrix}3 & 1\\ 1 & 3\end{bmatrix}$


se tiene,

\begin{equation}
(A-4 \textrm{I}) \vec{x} = \begin{bmatrix}-1 & 1\\ 1 & -1\end{bmatrix}\vec{x}=
\begin{bmatrix}-1 & 1\\ 1 & -1\end{bmatrix}\begin{bmatrix}1 \\ 1\end{bmatrix}=0
\end{equation}

\begin{equation}
(A-2 \textrm{I}) \vec{x} = \begin{bmatrix}1 & 1\\ 1 & 1\end{bmatrix}\vec{x}=
\begin{bmatrix}1 & 1\\ 1 & 1\end{bmatrix}\begin{bmatrix}-1 \\ 1\end{bmatrix}=0
\end{equation}

Por lo tanto, $\vec{x}_1=\begin{bmatrix}1 \\ 1\end{bmatrix}$ y  $\vec{x}_2=\begin{bmatrix}-1 \\ 1\end{bmatrix}$

Video - Forma de cálculo: https://www.youtube.com/watch?v=Gx0PaWI9eYo&list=PLIb_io8a5NB2DddFf-PwvZDCOUNT1GZoA&index=14

## Propiedades auto valores y auto vectores
- Matrices en $\mathbb{R}^{nxn}$ poseen $n$ auto valores (pueden ser complejos). Esto es, el rango es igual al número de auto valores no nulos
- La suma de todos los auto valores es igual a la traza: $\textrm{tr}(A)=\sum\limits_{i=1}^n\lambda_i$
- El producto de los auto valores es igual al determinante: $\textrm{det}(A)\prod\limits_{i=1}^n\lambda_i$
- Las matrices simétricas tienen auto valores reales
- Las matrices anti-simétricas tienen auto valores complejos (puros)
- Las matrices triangulares tienen sus auto valores en la diagonal, los cuáles pueden ser repetidos. Lo anterior puede generar que no existan múltiples auto vectores. (Nota: Una matriz triangular es un tipo de matriz cuadrada cuyos elementos por encima o por debajo de su diagonal principal son cero.)



**Recursos:**

* Video Auto-valores y auto-vectores: - 17 min
https://www.youtube.com/watch?v=PFDu9oVAE-g&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=14

* Solucionador de ecuaciones en linea (Eliminación de Gauss-Jordan): http://es.onlinemschool.com/math/assistance/equation/quadratic/

* Ejemplo de cálculo: https://aga.frba.utn.edu.ar/autovalores-autovectores-definiciones-propiedades/


In [ ]:
import numpy as np
from numpy import linalg as LA
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html#numpy.linalg.eig

def calcule(A):
    print("===================================================")
    print("A:")
    print(A)
    l, x = LA.eig(A)
    print("l-autovalores: ")
    print(l)
    print("x-autovectores: (Note que vienen normalizados)")
    print(x)
    # Prueba
    print("Prueba de resultados")

    print("A*x:")
    print(np.matmul(A,x))
    print("l*x: ")
    # en x los auto-vectores son columnas, por eso para multiplicarlos por los
    # auto-valores respectivos se hace este código y se genera una matriz ya
    # multiplicado cada auto-valor por su respectivo auto-vector
    result = []
    for i in range(len(l)):
        columna = l[i]*x[:,i]
        result.append(columna)
    # se transpone porque result quedó con los vectores en forma de fila y son
    # vectores columna (auto-vectores)
    result = np.array(result).transpose()
    print(result)

# main
calcule(np.array([[0.0, 1.0],
                  [1.0, 0.0]
                 ]) )

calcule( np.array([[3.0, 1.0], [1.0, 3.0]]) )
calcule(np.array([[3., 1.], [1., 3.]]) )
calcule(np.array([[3.0, 2.0, -1.0], [2.0, 3.0,1.0], [0.0,0.0,5.0]]) )
calcule(np.array([[3.0, 2.0, 1.0], [0.0, 1.0,0.0], [0.0,5.0,0.0]]) )
calcule(np.diag([1,2,3]) )


A:
[[0. 1.]
 [1. 0.]]
l-autovalores: 
[ 1. -1.]
x-autovectores: (Note que vienen normalizados)
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Prueba de resultados
A*x:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
l*x: 
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
A:
[[3. 1.]
 [1. 3.]]
l-autovalores: 
[4. 2.]
x-autovectores: (Note que vienen normalizados)
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Prueba de resultados
A*x:
[[ 2.82842712 -1.41421356]
 [ 2.82842712  1.41421356]]
l*x: 
[[ 2.82842712 -1.41421356]
 [ 2.82842712  1.41421356]]
A:
[[3. 1.]
 [1. 3.]]
l-autovalores: 
[4. 2.]
x-autovectores: (Note que vienen normalizados)
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Prueba de resultados
A*x:
[[ 2.82842712 -1.41421356]
 [ 2.82842712  1.41421356]]
l*x: 
[[ 2.82842712 -1.41421356]
 [ 2.82842712  1.41421356]]
A:
[[ 3.  2. -1.]
 [ 2.  3.  1.]
 [ 0.  0.  5.]]
l-autovalores: 
[5. 1. 5.]
x-autovectores: (Note que vienen normalizados)
[[ 0.