# Matemática para Ciencia de los Datos
# Trabajo Práctico 4

Profesor: Juan Luis Crespo Mariño (basado en trabajo previo del Prof. Dr. Luis Alexánder Calvo Valverde)

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: 19 de agosto del 2025, hora límite las 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. **Nombre_Estudiante_1**
1. **Nombre_Estudiante_2**


# Matemática para Ciencia de los Datos
# Trabajo Práctico 4

Profesor: Juan Luis Crespo Mariño (basado en trabajo previo del Prof. Dr. Luis Alexánder Calvo Valverde)

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: 19 de agosto del 2025, hora límite las 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. **Nombre_Estudiante_1**
1. **Nombre_Estudiante_2**



---

## Parte 1

Dada la siguiente matriz:

\begin{equation}
A= \begin{bmatrix}
   1.,2. \\
   3.,4.
\end{bmatrix}
\end{equation}




**Ejercicio 1.1 (25 puntos)**

En una celda de texto, calcule los auto-valores y deje planteada la ecuación para el cálculo de los los auto-vectores como los ejemplos vistos en clase. Debe mostrar todo el procedimiento.

$$
A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix},
\quad
A - \lambda I = 
\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} 
- \lambda \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} 
= \begin{pmatrix} 1 - \lambda & 2 \\ 3 & 4 - \lambda \end{pmatrix}
$$

$$
\left| \begin{matrix} 1 - \lambda & 2 \\ 3 & 4 - \lambda \end{matrix} \right| = 0
\quad\Rightarrow\quad
(1 - \lambda)(4 - \lambda) - 6 = 0
$$

$$
4 - \lambda - 4\lambda + \lambda^2 - 6 = 0
\quad\Rightarrow\quad
\lambda^2 - 5\lambda - 2 = 0
$$

<div align="center">Es una ecuación cuadrática</div>

$$
a\lambda^2 + b\lambda + c = 0 
\quad\Rightarrow\quad 
\lambda = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

$$
\lambda = \frac{5 \pm \sqrt{25 + 8}}{2}
\quad\Rightarrow\quad
\lambda_1 = \frac{5 + \sqrt{33}}{2},\quad
\lambda_2 = \frac{5 - \sqrt{33}}{2}
$$

**Ejercicio 1.2 (25 puntos)**

En una celda de código y utilizando la función eig de numpy, calcule los auto-valores y auto-vectores y haga las operaciones en el código para mostrar que se cumple: $A\,\vec{x} = \lambda\vec{x}$ (No olvide las pequeñas posibles diferencias por precisión de la representación numérica).


In [1]:
import numpy as np
from numpy import linalg as LA
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html#numpy.linalg.eig

def calcule(A):
    print("===================================================")
    print("A:")
    print(A)
    l, x = LA.eig(A)
    print("l-autovalores: ")
    print(l)
    print("x-autovectores: (Note que vienen normalizados)")
    print(x)
    # Prueba
    print("Prueba de resultados")

    print("A*x:")
    print(np.matmul(A,x))
    print("l*x: ")
    # en x los auto-vectores son columnas, por eso para multiplicarlos por los
    # auto-valores respectivos se hace este código y se genera una matriz ya
    # multiplicado cada auto-valor por su respectivo auto-vector
    result = []
    for i in range(len(l)):
        columna = l[i]*x[:,i]
        result.append(columna)
    # se transpone porque result quedó con los vectores en forma de fila y son
    # vectores columna (auto-vectores)
    result = np.array(result).transpose()
    print(result)

A = np.array([[1, 2], [3, 4]])
calcule(A)

A:
[[1 2]
 [3 4]]
l-autovalores: 
[-0.37228132  5.37228132]
x-autovectores: (Note que vienen normalizados)
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Prueba de resultados
A*x:
[[ 0.30697009 -2.23472698]
 [-0.21062466 -4.88542751]]
l*x: 
[[ 0.30697009 -2.23472698]
 [-0.21062466 -4.88542751]]



---

## Parte 2


Realice lo siguiente: **(40 puntos)**
1. Similar a los ejemplos vistos, aplíquele la estrategia PCA a los datos en el archivo adjunto "data_banknote_authentication.csv" (el $Y$ corresponde a la columna llamada clase).
1. En este caso use los tres primeros componentes principales (no dos como en el ejemplo).
1. El ejercicio termina graficando la varianza acumulada versus los componentes principales.

---



___

## Parte 3

Como en el segundo gráfico del cuaderno visto en clase sobre PCA, grafique los tres mayores componentes principales utilizando la bibioteca **plotly** https://plotly.com/python/3d-scatter-plots/  **(10 puntos)**


___